#! /bin/bash

set -Eeuo pipefail;

password="";
default_branch="master";

# Usage instructions
print_usage() {
	echo "";
	echo "Usage:";
	echo "";
	echo "./setup --pwd <value> [--help] [--default-branch <branch_name>]";
	echo "";
	echo "--pwd <value>";
	echo "	Password for the Git server account. Used for SSH as well.";
	echo "	Value: A string. An empty string is not allowed.";
	echo "	Requirement: Always";
	echo "";
	echo "--default-branch <branch_name>";
	echo "	Optionally specify the default branch that Git should use for the initial branch.";
	echo "	Value: A string. Default value is 'master'.";
	echo "	Requirement: Optional";
	echo "";
	echo "--help";
	echo "	Print this command usage instruction.";
	echo "	Value: No value should be entered.";
	echo "	Requirement: Optional";
	echo "";
}

# Handle arguments
if [[ "$#" -gt 0 ]]; then
	case "$1" in
		"--pwd")
			password=$2;
			shift;
			shift;
			;;
		"--default-branch")
			default_branch=$2;
			shift;
			shift;
			;;
		"--help")
			print_usage;
			exit 0;
			;;
		*)
			echo "Error: Invalid argument $2.";
			exit 1;
			;;
	esac;
else
	echo "Error: Missing argument(s).";
	print_usage;
	exit 1;
fi;

if [[ "${password}" == "" ]]; then
	echo "Error: Please enter a password.";
	print_usage;
	exit 1;
fi;

if [[ "${default_branch}" == "" ]]; then
	echo "Error: Please enter a default branch name";
	print_usage;
	exit 1;
fi;

if [[ "${default_branch}" == "master" ]]; then
	echo "";
	echo "NOTE: Using 'master' as the default branch name.";
	echo "";
fi;

# Install dependencies
sudo apt-get update;
sudo apt-get install -y git openssh-server net-tools;

# Create new user 'git' (for security)
sudo useradd --create-home -d /home/git --user-group --shell /bin/bash git;

# Set password for user 'git'
echo git:"${password}" | sudo chpasswd;

# Create directory for repositories
sudo mkdir /srv/git;
sudo chown -R git:git /srv/git;

# Configure the default branch for Git to use when a repository is created by the user 'git'
printf "[init]\n\tdefaultBranch = ${default_branch}\n" > /home/git/.gitconfig;
chown git:git /home/git/.gitconfig;

# Post-install instructions
echo "";
echo "Setup successful!";
echo "A Git server has been set up with a new user and group called 'git'.";
echo "Repositories have to be stored at /srv/git.";
echo "Password for user 'git': ${password}";
echo "SSH access: ssh git@$(hostname)";
echo "Server IP: $(hostname -I)";
echo "";
echo "For further instructions, please refer to https://github.com/HarshKapadia2/git-server/blob/main/README.md .";
echo "";

